server {
    listen 80;
    server_name algovisualizer.dev www.algovisualizer.dev;

    # Serve the React application
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy for the backend API
    # This matches the /trace route and sends it to the 'backend' container
    # resolving CORS and weird address issues on deployment!
    location /trace {
        proxy_pass http://backend:8080/trace;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
